export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

const responses: Record<string, string> = {
  default: `That's a rich question. The literature is divided on this, with at least two distinct schools of thought. Early theoretical work established the foundational mechanism, but empirical evidence — especially from developing economies — reveals significant heterogeneity. Institutional quality, legal frameworks, and data availability all moderate the relationship. The most cited papers suggest the effect is context-dependent and non-linear, which means your research context matters enormously for the interpretation.`,
};

const fieldResponses: Record<string, Record<string, string>> = {
  'financial stability': {
    'why do findings differ': `Great question. The divergence in Financial Stability findings stems from three core sources:\n\n**1. Definitional inconsistency** — Some studies use Z-scores, others use NPL ratios, CAR, or systemic risk measures. These capture fundamentally different dimensions of stability.\n\n**2. Sample heterogeneity** — Pooling OECD banks with SSA banks ignores massive institutional differences. The competition-stability nexus, for instance, is positive in developed markets but ambiguous or negative in weak-institution environments.\n\n**3. Endogeneity** — Stability and most explanatory variables (capital, competition, regulation) are simultaneously determined. Studies not using IV, GMM, or natural experiments risk reverse causality.\n\nThe most honest answer: many contradictions in this literature are **methodological artifacts**, not true disagreements about the underlying reality.`,
    'best methodology': `For a panel study on banking stability, the methodological hierarchy looks like this:\n\n**Tier 1 — System GMM (Arellano-Bond/Blundell-Bond)**\n→ Handles endogeneity, unobserved heterogeneity, and dynamic persistence of Z-scores\n→ Use 2-step with Windmeijer-corrected SEs\n→ Validate with Hansen J-stat and AR(2) test\n\n**Tier 2 — Panel Fixed Effects with IV**\n→ Appropriate if your focal variable is plausibly exogenous\n→ Hausman test to choose FE over RE\n\n**Tier 3 — Quantile Panel Regression**\n→ Captures heterogeneous effects across the stability distribution\n→ Reveals if results hold only for already-fragile banks\n\nAvoid OLS — it's inconsistent for dynamic panels and will overstate persistence.`,
    'research gap': `The most underexplored gaps in Financial Stability as of 2024:\n\n🔴 **Climate Risk → Bank Balance Sheets in SSA** — Physical risk (agricultural loan exposure) and transition risk (carbon-intensive sectors) have no comprehensive panel treatment for Africa.\n\n🔴 **FinTech Deposit Migration** — Digital wallets pulling deposits from traditional banks affect the LDR and liquidity management in ways the literature hasn't modeled.\n\n🟡 **Governance as Moderator** — Most studies include WGI as a control. Nobody has properly modeled it as an interaction term asking: "Does regulatory quality change the slope of the capital-stability relationship?"\n\n🟡 **Post-COVID Structural Breaks** — Bai-Perron tests on pre/post-2020 panels are conspicuously absent.\n\nAny of these would make a strong PhD contribution.`,
    default: `The Financial Stability literature has evolved dramatically since Minsky's Financial Instability Hypothesis (1977). The field now integrates banking theory, macroprudential regulation, and institutional economics. Key debates revolve around: (1) the competition-stability nexus, (2) the role of capital regulation, (3) deposit insurance design, and (4) systemic risk measurement. The methodological frontier has shifted toward System GMM, quantile approaches, and network models. What specific aspect would you like to explore?`,
  },
  'central bank independence': {
    'why do findings differ': `The CBI-inflation literature shows a striking pattern: strong results in OECD countries, weak or null results in developing economies. Here's why:\n\n**De jure vs. de facto independence** — Legal CBI indices (Cukierman-Webb-Neyapti) measure what's written in central bank laws. But in many SSA and low-income countries, political interference operates informally — through budget pressures, informal appointments, or fiscal dominance. The gap between legal and actual independence explains most of the divergence.\n\n**Fiscal dominance** — When governments run large deficits, central banks are often pressured to monetize debt regardless of their formal mandate. Sargent & Wallace (1981) showed that in fiscally dominant regimes, tight monetary policy today may actually increase future inflation.\n\n**Sample period effects** — Pre-1990 studies show stronger CBI-inflation links because the variation in inflation was larger. Post-2008 QE has muddied the relationship in developed economies too.`,
    default: `Central Bank Independence research has moved through several waves. The 1990s empirical work (Alesina, Cukierman) found robust negative correlations between CBI and inflation in OECD countries. The 2000s brought skepticism about developing economies, where de facto independence often diverges from de jure indices. Post-GFC, the debate shifted to whether CBI is compatible with financial stability mandates, unconventional policy tools, and accountability demands. Current frontiers include CBDC governance, climate mandates, and the political economy of CBI erosion. What would you like to dig into?`,
  },
  'climate finance': {
    'why do findings differ': `Climate finance findings diverge for three interconnected reasons:\n\n**1. Scenario dependency** — Whether you use an orderly 2°C transition, a disorderly scenario, or a hot-house world produces radically different loss estimates. ECB stress tests and Battiston's network models assume different shock magnitudes and transmission speeds.\n\n**2. Greenium measurement** — Comparing green vs. conventional bond yields requires exact maturity, currency, and issuer matching. Studies that don't match on observable characteristics find spurious premia or discounts.\n\n**3. Second-order effects ignored** — Direct portfolio loss models miss network contagion — fire sales, interbank exposures, and supply-chain cascades can amplify first-round losses 3–5×. Studies using only direct exposure systematically underestimate systemic risk.\n\nThe honest conclusion: climate risk in finance is real, but the magnitude is deeply uncertain and scenario-dependent.`,
    'best methodology': `Climate finance research requires matching methods to the specific research question:\n\n**For physical risk → bank NPLs:** Panel ARDL or System GMM with climate shock variables (SPEI drought index, flood occurrence, temperature anomaly) and bank-level data from BankFocus or local central bank databases.\n\n**For green bond pricing:** Matched-pair event study — control bonds must be identical on maturity, currency, credit rating, and issuer type. Propensity score matching helps construct the counterfactual.\n\n**For systemic climate risk:** Network contagion models (Battiston framework) — build interbank exposure matrix, apply climate-scenario shocks to exposed portfolios, simulate cascading defaults.\n\n**For TCFD disclosure effects:** DiD around mandatory disclosure adoption — compare firms in jurisdictions that adopted TCFD vs. voluntary adopters.`,
    'research gap': `The highest-opportunity gaps in Climate Finance for 2024–2026:\n\n🔴 **Physical risk transmission to SSA bank balance sheets** — Agricultural loan portfolios in SSA carry enormous climate exposure (drought, flood) but no comprehensive panel study exists. Opportunity score: 96/100.\n\n🔴 **Petro-economy transition risk quantification** — Nigeria, Angola, and Ghana face sovereign and banking sector risk from global decarbonization. Portfolio-level stress tests haven't been done.\n\n🟡 **Green bond market infrastructure in Africa** — Why does Africa issue <1% of global green bonds? Demand-side (institutional investor base), supply-side (certification costs), and regulatory barriers need decomposition.\n\n🟡 **Climate finance and financial inclusion synergies** — Can green SME loans and agricultural climate bonds simultaneously advance climate and inclusion goals? Evidence is entirely absent.`,
    default: `Climate Finance is one of the fastest-growing fields in financial economics, catalyzed by the Paris Agreement (2015) and Carney's "Tragedy of the Horizon" speech. The field sits at the intersection of asset pricing (carbon beta, greenium), banking regulation (stress tests, capital charges for brown assets), and development finance (green bond markets, climate funds). Key theoretical frameworks include the Climate Minsky Moment, Stranded Asset Theory, and Physical Risk Transmission channels. The methodological frontier spans scenario-based stress testing, network contagion models, and event studies around climate policy announcements. What aspect would you like to explore?`,
  },
  'monetary policy': {
    'why do findings differ': `Monetary policy research diverges for reasons rooted in both methodology and context:\n\n**1. Identification challenges** — Central banks react to the economy and the economy reacts to central banks simultaneously. Identifying the causal effect of a rate change requires a credible shock — studies using recursive SVAR, narrative shocks (Romer & Romer), or high-frequency identification show smaller, more credible effects than simple VARs.\n\n**2. The ZLB changes everything** — Research on conventional rate policy doesn't extrapolate to the zero lower bound. QE works through different channels (portfolio balance, signaling) than normal rate cuts, and studies conflating the two produce confusing results.\n\n**3. Transmission heterogeneity** — Monetary policy works through banks, bond markets, and exchange rates. In SSA where bank dominance is high, money markets are shallow, and dollarization is significant, transmission is severely impaired vs. OECD economies.`,
    'best methodology': `Methodology hierarchy for monetary policy research:\n\n**For transmission effects:** Structural VAR (SVAR) with recursive identification or sign restrictions. Jordà local projections for robustness — they're more flexible and don't impose lag structure.\n\n**For SSA/developing economy transmission:** Panel SVAR or single-country Bayesian VAR when data is short. Narrative approach (reading minutes/MPC decisions) helps construct cleaner shock series.\n\n**For policy rule estimation:** GMM estimation of Taylor-type reaction functions — allows instrument sets that address feedback from output and inflation.\n\n**For QE/unconventional policy:** Event study around announcement dates using high-frequency bond and equity data. Avoid macro VARs for QE — the identification assumptions break down.`,
    'research gap': `Critical gaps in Monetary Policy research:\n\n🔴 **Transmission in high-informality economies** — When 60%+ of economic activity is informal, standard bank-credit channels reach only a fraction of the economy. Quantifying this impairment for African economies is largely undone.\n\n🔴 **CBDC and monetary policy transmission** — How retail CBDC affects money multipliers, bank deposit funding, and interest rate pass-through is theoretically modeled but empirically untested.\n\n🟡 **Post-COVID inflation decomposition for LMICs** — Supply-side vs. demand-side decomposition of 2021–2023 inflation in African and Asian economies lags the US/EU literature by 2–3 years.\n\n🟡 **Monetary policy and inequality** — The distributional effects of tightening cycles (via asset prices, unemployment, and debt service) in developing economies are understudied.`,
    default: `Monetary Policy research spans from the monetarist revolution of the 1970s through the New Keynesian synthesis and the extraordinary interventions of the post-2008 era. Key theoretical pillars include Woodford's interest rate rule framework, the Bernanke credit channel, and forward guidance theory. The empirical literature is dominated by SVAR identification debates and the growing recognition that transmission differs dramatically between advanced and developing economies. Post-COVID inflation has reopened fundamental questions about central bank credibility, r-star, and the limits of conventional frameworks. What specific dimension would you like to explore?`,
  },
  'blockchain banking': {
    'why do findings differ': `Blockchain/crypto finance findings are unusually context-sensitive because the market itself is rapidly evolving:\n\n**1. Sample period dominates everything** — Pre-2020 crypto-stock correlations are near zero. Post-2021, they spike. Studies using different windows get radically different answers about diversification benefits.\n\n**2. Design-dependent CBDC conclusions** — Whether CBDC causes bank disintermediation depends entirely on design (holding limits, remuneration, wholesale vs. retail). Studies modeling different CBDC architectures reach opposite conclusions.\n\n**3. DeFi measurement challenges** — TVL is easily manipulated through circular liquidity. True economic activity in DeFi is much smaller than headline TVL suggests, but measurement standards don't exist yet.\n\nThe honest assessment: this is a rapidly evolving system, and most empirical findings have a 6–18 month shelf life before a new market structure renders them obsolete.`,
    'best methodology': `Blockchain/crypto finance methods depend on the question:\n\n**For crypto-traditional market contagion:** DCC-GARCH models capturing time-varying conditional correlations. Test for regime-switching during crisis periods specifically.\n\n**For CBDC policy design:** Agent-based models (ABM) simulating household adoption decisions under different interest rate and holding limit parameters. DSGE models for macro-level disintermediation scenarios.\n\n**For DeFi systemic risk:** Network analysis — map protocol interdependencies, identify concentration (e.g., single collateral asset underpinning multiple protocols), simulate cascade failures.\n\n**For regulatory event effects:** High-frequency event study around specific dates (SEC rulings, exchange failures like FTX). Use CARs with cross-sectional asset controls.`,
    default: `Blockchain Banking research spans DeFi economics, CBDC monetary theory, crypto asset pricing, and regulatory design. The field emerged from Bitcoin's 2008 whitepaper but accelerated with the 2020 DeFi explosion and the 2019–2022 global CBDC sprint triggered by Libra. Key theoretical tensions: does DeFi disintermediate banking or complement it? Do CBDCs boost monetary policy transmission or crowd out commercial bank deposits? Does crypto offer genuine diversification or is it a risk-on asset? The BIS, IMF, and ECB now produce substantial empirical work in this space. What aspect would you like to explore?`,
  },
  'ai in education': {
    'why do findings differ': `AI EdTech research shows highly variable effect sizes for structural reasons:\n\n**1. Baseline heterogeneity** — AI tools show larger gains in low-quality education baselines (where the counterfactual is poor instruction) and smaller gains where teaching quality is already high. Many US studies find modest effects; LMIC studies with weaker baselines find larger gains.\n\n**2. Implementation fidelity** — The same AI platform deployed with strong teacher training shows 2–3× the learning gains vs. deployment without support. Studies that don't measure implementation quality conflate platform and deployment effects.\n\n**3. Outcome measurement** — Short-term test score gains are the most common outcome. Long-term retention, transfer to novel problems, and metacognitive development are rarely measured and may tell a different story.`,
    'best methodology': `For AI EdTech research, rigor requires:\n\n**Gold standard:** School-level RCT with random assignment of AI vs. control condition. Pre-register the primary outcome. Measure implementation fidelity alongside student outcomes.\n\n**When RCT is infeasible:** Regression discontinuity around eligibility cutoffs for AI programs, or difference-in-differences exploiting staggered rollout across schools/districts.\n\n**For learning process analysis:** Log-data learning analytics — clickstream, time-on-task, error pattern, and help-seeking data. Use sequence mining and survival analysis to identify disengagement predictors.\n\n**For equity analysis:** Quantile treatment effects — does AI help all students equally, or only those above a minimum digital literacy threshold? Always stratify by SES and prior attainment.`,
    'research gap': `Critical gaps in AI Education research:\n\n🔴 **AI tutoring for low-bandwidth African classrooms** — Essentially all large-scale EdTech research comes from high-connectivity contexts. Offline-capable, lightweight AI for SSA schools is theoretically underdeveloped and practically urgent. Opportunity: 97/100.\n\n🔴 **LLM hallucination auditing in subject tutoring** — GPT-4 and similar models used as tutors confidently produce wrong answers. Frequency and severity of factual errors across subjects and grade levels is not systematically benchmarked.\n\n🔴 **AI bias in opportunity allocation** — Automated early-warning systems and recommendation algorithms may encode racial/SES biases. Auditing evidence is thin, especially outside Western contexts.\n\n🟡 **Long-term outcomes beyond test scores** — What happens to critical thinking, creativity, and labor market outcomes 5–10 years after AI-assisted schooling? Zero longitudinal evidence exists.`,
    default: `AI in Education research spans intelligent tutoring systems (ITS), learning analytics, adaptive learning platforms, and now large language model tutors. The theoretical foundations include Vygotsky's Zone of Proximal Development, Bloom's mastery learning, and Sweller's cognitive load theory. Empirically, the field shows wide variability in effect sizes — from near-zero in well-resourced contexts to significant gains where baseline quality is poor. Equity is the central policy concern: evidence is mixed on whether AI narrows or widens achievement gaps depending on implementation design. The arrival of LLMs as tutors in 2022–2023 created a step-change in capability but introduced new risks around accuracy, dependency, and academic integrity. What would you like to explore?`,
  },
};

export function getMockResponse(field: string, userMessage: string): string {
  const fieldKey = field.toLowerCase().trim();
  const msgKey = userMessage.toLowerCase();

  const fieldData = fieldResponses[fieldKey];
  if (fieldData) {
    for (const [key, resp] of Object.entries(fieldData)) {
      if (key !== 'default' && msgKey.includes(key)) return resp;
    }
    return fieldData.default ?? responses.default;
  }

  if (msgKey.includes('gap') || msgKey.includes('underexplored')) {
    return `In the ${field} literature, the most pressing gaps are methodological (non-linear models rarely applied), geographic (SSA and South Asia under-represented), and temporal (post-2020 evidence thin). Digital transformation variables are almost entirely missing from empirical models. Any of these represents a viable research contribution.`;
  }
  if (msgKey.includes('method') || msgKey.includes('gmm') || msgKey.includes('regression')) {
    return `For ${field} research, methodology choice depends on your data structure. Panel data with endogenous regressors → System GMM. Time-series with cointegration → ARDL bounds test. Policy evaluation with treatment/control groups → Difference-in-Differences. Heterogeneous treatment effects → Quantile regression. The key question is whether your focal variable is endogenous — if so, GMM or IV is essential.`;
  }
  if (msgKey.includes('theory') || msgKey.includes('theoretical')) {
    return `The theoretical landscape of ${field} is contested. Foundational frameworks from the 1980s–1990s established the core mechanisms, but institutional and behavioral extensions from the 2000s revealed that context mediates almost everything. The emerging synthesis is that structural factors (institutions, development level, governance) determine which theoretical predictions hold empirically.`;
  }

  return `The ${field} literature shows significant evolution over the past four decades. Early theoretical work established mechanisms that empirical research has since both confirmed and complicated. The most important insight is that results are highly context-dependent — developed vs. developing economies, pre vs. post-crisis periods, and strong vs. weak institutional environments all produce systematically different findings. What specific angle — theory, methodology, contradictions, or gaps — would you like to explore?`;
}

export const suggestedQuestions = [
  'Why do findings differ across regions?',
  'What is the best methodology for this topic?',
  'What are the key research gaps?',
  'Which theories are most contested?',
  'How has this field evolved since 2008?',
  'What variables are most commonly used?',
];
